const en = {
  Profile: "Profile",
  header: "Language",
  language: "Select a Language",
  EditProfile: "EditProfile",
  Notification: "Notification ",
  Payment: "Payment",
  Privacy: "Privacy",
  Male: "Male",
  Female: "Female",
  Others: "Others",
  Appointment: "Appointment",
  "Enter Your Name": "Enter Your Name",
  "Enter Your Email": "Enter Your Email",
  Update: "Update",
  "Privacy Policy": "Privacy Policy",
  Sound: "Sound",
  Vibrate: "Vibrate",
  "Special Offers": "Special Offers",
  "Promo & Discount": "Promo & Discount",
  "New Service Available": "New Service Available",
  "Personal Information We Collect": "La información personal que recopilamos",
  "Our salon app Razor Cut is owned and operated by us. We are committed to protecting the privacy of our users .This Privacy Policy outlines how we collect, use, and protect your personal information when you use the App.":"Our salon app Razor Cut is owned and operated by us. We are committed to protecting the privacy of our users This Privacy Policy outlines how we collect, use, and protect your personal information when you use the App."
};

const sp = {
    Profile:"Perfil",
    header:"idioma",
    language: "Selecciona un idioma",
   "EditProfile":"Edit arperfil",
    Notification:" Notificación",
    Payment:"Pago",
    Privacy:" Privacidad",
    Male:"Masculina",
    Female:"Femenina",
    Others:" otras(feminine)",
     Appointemnt:"cita",
    "Enter Your Name" :"Introduzca su nombre",
    "Enter Your Email": "escribe tu correo electronico",
    Update:"Actualizar",
    "Privacy Policy":"Política de privacidad",
    Sound:"Sonido",
    Vibrate: "Vibrar",
    "Special Offers":"Oferta especial",
    "Promo & Discount": "Promoción y descuento",
    "New Service Available":"Nuevo servicio disponible",
    "Personal Information We Collect": "আমরা কীভাবে ব্যক্তিগত তথ্য সংগ্রহ করি",
    "Our salon app Razor Cut is owned and operated by us. We are committed to protecting the privacy of our users This Privacy Policy outlines how we collect, use, and protect your personal information when you use the App.":"Nuestra aplicación de salón, Razor Cut, es propiedad y está operada por nosotros. Estamos comprometidos a proteger la privacidad de nuestros usuarios. Esta Política de Privacidad describe cómo recopilamos, utilizamos y protegemos su información personal cuando utiliza la aplicación."


};

const bn = {
  Profile: "প্রোফাইল",
  header: "ভাষা",
  language: "একটি ভাষা নির্বাচন করুন",
  EditProfile: "জীবন বৃত্তান্ত সম্পাদনা",
  Notification: "বিজ্ঞপ্তি",
  Payment: "পেমেন্ট",
  Privacy: " গোপনীয়তা",
  Male: "পুরুষ",
  Female: "মহিলা",
  Others: " অন্যান্য",
  Appointment: "অ্যাপয়েন্টমেন্ট",
  "Enter Your Name": "আপনার নাম লিখ",
  "Enter Your Email": "আপনার ইমেইল লিখুন",
  Update: "আপ টু ডেট",
  "Privacy Policy": "গোপনীয়তা নীতি",
  Sound: "শব্দ",
  Vibrate: "কম্পন",
  "Special Offers": "স্পেশাল অফার",
  "Promo & Discount": "প্রচার এবং ডিসকাউন্ট",
  "New Service Available": "নতুন পরিষেবা উপলব্ধ",
  "Personal Information We Collect": "Personal Information We Collect",
  "Our salon app Razor Cut is owned and operated by us. We are committed to protecting the privacy of our users .This Privacy Policy outlines how we collect, use, and protect your personal information when you use the App.": "আমাদের সেলুন অ্যাপ Razor Cut আমাদের দ্বারা মালিকানাধীন এবং চালান করা হয়। আমরা আমাদের ব্যবহারকারীদের গোপনীয়তা রক্ষা করতে প্রতিশ্রুতিবদ্ধ। এই গোপনীয়তা নীতি বর্ণনা করে যে ভাবে আমরা আপনার ব্যক্তিগত তথ্য সংগ্রহ করি, ব্যবহার করি এবং সুরক্ষা করি যখন আপনি অ্যাপটি ব্যবহার করেন।"
};
export { en, sp, bn };